name = "QWignerSymbols"
uuid = "a6ec71dc-95d1-4ca4-9dd3-50060f27aa2b"
authors = ["lkdvos <lukas.devos@ugent.be>"]
version = "0.1.0"

[deps]
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
HalfIntegers = "1.6.0"
LinearAlgebra = "1.11.0"
TensorKitSectors = "0.3.4"
TensorOperations = "5.4.0"
WignerSymbols = "2"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"

[targets]
test = ["TensorKitSectors", "TensorOperations", "Test", "TestExtras", "LinearAlgebra"]
